#version: '3.8'
#
#services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: 'django_hotel'
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    ports:
#      - 8001:8000
#    env_file:
#      - .env
#    depends_on:
#      - db
#  db:
#    image: postgres:16-alpine
#    container_name: 'hotel_db'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#
#volumes:
#  postgres_data:
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hotel_db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: amir1234
    ports:
      - "5433:5432"
  web:
    build: .
    container_name: django_hotel
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
